### ISSUE TITLE
data loader problem

### ISSUE THREAD

**Issue by alighofrani95** [aayushm107/VStegNET#1]
I'm so interested in your great paper VStegNET and try to reimplement from your repo
after downloading UCF-101 and put it in the directory as explained in the readme file, I faced with the error below 

"""
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
Traceback (most recent call last):
  File "stego_net.py", line 627, in <module>
    m.train()
  File "stego_net.py", line 354, in train
    for covers, secrets, c_name, s_name, epoch, batch in generator():
  File "stego_net.py", line 347, in generator
    frs = sorted(os.listdir(c_path), key=lambda x: int(x.split('.')[0]))[:t * self.frames_per_batch]
  File "stego_net.py", line 347, in <lambda>
    frs = sorted(os.listdir(c_path), key=lambda x: int(x.split('.')[0]))[:t * self.frames_per_batch]
ValueError: invalid literal for int() with base 10: ''
"""

Do you use the default name of videos or rename them before loading them? 

indeed if it's possible please add a requirement file to help reimplement the project with the same results...

thanks a lot

**Comment by aamixsh** [comment]
Please extract frames from videos, and rename every object (videos and frames of videos) with numbers. That's how it is sorted frame-wise.

**Comment by alighofrani95** [comment]
thank you for your fast replying
based on your guide, I extract frames from videos and now I faced with loading file error.

Could you please share the dataset loader and requirements file

**Comment by aamixsh** [comment]
It's all there in these set of codes. For frame extraction you can use _ffmpeg_. I am a bit busy so can not put up the requirement file instantly, will do that in some time.

**Comment by 2459122312** [comment]
> thank you for your fast replying based on your guide, I extract frames from videos and now I faced with loading file error.
> 
> Could you please share the dataset loader and requirements file

Hello,have you solved this problem?

**Comment by 2459122312** [comment]
> It's all there in these set of codes. For frame extraction you can use _ffmpeg_. I am a bit busy so can not put up the requirement file instantly, will do that in some time.

Could you please share the dataset loader and requirements file?Thank you .

**Comment by aamixsh** [comment]
Hi,

I'm really sorry about this but I don't have the requirements file. This code was written quickly in a prototype fashion without documentation and I regret it now. It was written at the start of 2019 so I think tensorflow version 1.10 or something should work. Although I don't remember using very niche functions there so most of the code should work in more recent versions too. I'm afraid if there's an error now, it will have to be fixed manually. 

My best recommendation would be to just look at the model architecture in the paper and reimplement it in a current version of tensorflow or pytorch. This code can be used as template for that, as I assure you it worked when I wrote it.

I will try to find some time to fix some obvious issues here and maybe get a requirements file that works (but assume that won't work).

All the best!

**Comment by 2459122312** [comment]
HI,
recently I have tryed my best to  reimplement your results according to your readme file, but I failed. 
I'm so interested in your great paper VStegNET . Could you please share the dataset loader and requirements file?Thank you
